[project]
name = "mustwebui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tohboeh5", email = "47549972+tohboeh5@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mustwebui = "mustwebui:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
